function angles = angleImport(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EMSTFX = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  EMSTFX = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  emstfx = importfile("C:\Users\nfq3bd\Desktop\Research\Sex Scaling\Biodex\Biodex Data\10_14_2022\em_st_fx.txt", [37, 37]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Oct-2022 10:33:41

%% Input handling
if nargin < 2
    dataLines = [37, 37];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Set", "Rep", "mSec", "TORQUE", "POSITION", "POS_ANAT", "VELOCITY", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["VarName9", "VarName10", "VarName11", "VarName12", "VarName13"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName9", "VarName10", "VarName11", "VarName12", "VarName13"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Set", "TrimNonNumeric", true);
opts = setvaropts(opts, "Set", "ThousandsSeparator", ",");

% Import the data
a= readtable(filename, opts);
idx = ~ismissing(a{1,:}) ;
angles = a{1,idx} ;

info = trialDataImport(filename);
comp.joint = string(info(19)) ; % Joint
if contains(comp.joint,'Ankle')==1;
    while length(angles) > 4
        angles(5) = [];
    end
elseif contains(comp.joint,'Knee')==1;
    while length(angles) > 4
        angles(5) = [];
    end
elseif contains(comp.joint, 'Hip')==1;
        angles(9) = [];
        angles(7) = [];
        angles(5) = [];
end

end