function [data,fdata,pmax,tmax,mmax,smax,cmax,metadata] = importBiodex(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [SET, REP, MSEC, TORQUE, POSITION, POS_ANAT, VELOCITY] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [SET, REP, MSEC, TORQUE, POSITION, POS_ANAT, VELOCITY] =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [Set, Rep, mSec, TORQUE, POSITION, POS_ANAT, VELOCITY] = importfile("C:\Users\nfq3bd\Desktop\Research\Sex Scaling\Biodex\Biodex Data\9_9_2022\Knee_calf.txt", [53, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Sep-2022 10:51:01
% [data,fdata,pmax,tmax,mmax,smax,cmax,metadata] = importBiodex(

%% Input handling
opts = delimitedTextImportOptions("NumVariables", 8, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, 2];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "Rep", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8"];
opts.SelectedVariableNames = "Rep";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Rep", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Rep", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8"], "EmptyFieldRule", "auto");

% Import the data
csub = readmatrix(filename, opts);

% Clear temporary variables
clear opts

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [53, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Set", "Rep", "mSec", "TORQUE", "POSITION", "POS_ANAT", "VELOCITY", "VarName8", "VarName9"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "VarName9", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName9", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Set", "TrimNonNumeric", true);
opts = setvaropts(opts, "Set", "ThousandsSeparator", ",");

%% Import the data
tbl = readtable(filename, opts);
ind.rep1 = ((tbl.Rep== 1)); % Finds Rep 1
ind.rep2 = ((tbl.Rep== 2)); % Finds Rep 2
angles = angleImport(filename); % Imports the angles for the joint
if length(angles) == 4
    for na = 1:length(angles)
        ind.(['a',num2str(angles(1,na))]) = (tbl.Set==na);
        cangle = (['a',num2str(angles(1,na))]); % Sets current angle
        for nReps = 1:2
            crep = ['rep',num2str(nReps)]; % Sets current rep
            itrial = (ind.(cangle)) & (ind.(crep)); % Creates the trial to be used by looking for the
            data.(cangle).(crep) = [tbl.mSec(itrial),tbl.TORQUE(itrial)]; % Saves data for time and torque
            % Data Filter
            w_coff1 =20; w_samp = 100;
            [b1,a1] = butter(2,(w_coff1/(w_samp/2)),'low');
            fdata.(cangle).(crep)(:,2) = filtfilt(b1,a1,data.(cangle).(crep)(:,2));
            fdata.(cangle).(crep)(:,1) = data.(cangle).(crep)(:,1);
            if sum(fdata.(cangle).(crep)(:,2)) > 0 % Checks to see if the data is positive
                % Max Calculations
                [cmax.(cangle).(crep),s] = max(fdata.(cangle).(crep)(:,2));
                [c,~] = size(fdata.(cangle).(crep)(:,2));
                if s < 50
                    mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(1:100,2));
                else
                    mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s-49:s+50,2));
                end
                if s > c-100
                    swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(end-100:end,2));
                else
                    swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s:s+99,2));
                end
            elseif sum(fdata.(cangle).(crep)(:,2)) < 0 % Checks to see if the data is negative
                % Max Calculations
                [cmax.(cangle).(crep),s] = max(-fdata.(cangle).(crep)(:,2));
                [c,~] = size(fdata.(cangle).(crep)(:,2));
                if s < 50
                    mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(1:100,2));
                else
                    mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s-49:s+50,2));
                end
                if s > c-100
                    swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(end-100:end,2));
                else
                    swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s:s+99,2));
                end
            else % Takes care of any empty fields (lost data, excluded data, ect)
                cmax.(cangle).(crep) = 0; % Sets the empty field to 0 to avoid issues for max and average
            end
        end
        pmax.(cangle)(1,1) = max(abs(cmax.(cangle).rep1),abs(cmax.(cangle).rep2));
        tmax.(cangle) = (cmax.(cangle).rep1+cmax.(cangle).rep2)/2; % Manual calculation of the max for each angle
        if pmax.(cangle) == cmax.(cangle).rep1
            mmax.(cangle) = mdmax.(cangle).rep1;
            smax.(cangle) = swmax.(cangle).rep1;
            pmax.(cangle)(1,2) = 1;
        else
            mmax.(cangle) = mdmax.(cangle).rep2;
            smax.(cangle) = swmax.(cangle).rep2;
            pmax.(cangle)(1,2) = 2;
        end
    end
else
    % Thresholds based off of previous traces with different true and false spikes
    peakDropMax = 50; % difference between peak and min in the next half of a second
    secondPeak = 20; % difference between the min and the data value at 1.5 seconds into the trial
    for na = 1:2:length(angles)
        ind.(['a',num2str(angles(1,na))]) = (tbl.Set==na);
        cangle = (['a',num2str(angles(1,na))]); % Sets current angle
        crep = ['rep',num2str(1)]; % Sets current rep
        itrial = (ind.(cangle)); % Creates the trial to be used
        data.(cangle).(crep) = [tbl.mSec(itrial),tbl.TORQUE(itrial)]; % Saves data for time and torque
        % Data Filter
        w_coff1 =20; w_samp = 100;
        [b1,a1] = butter(2,(w_coff1/(w_samp/2)),'low');
        fdata.(cangle).(crep)(:,2) = filtfilt(b1,a1,data.(cangle).(crep)(:,2));
        fdata.(cangle).(crep)(:,1) = data.(cangle).(crep)(:,1);
        if sum(fdata.(cangle).(crep)(:,2)) > 0 % Checks to see if the data is positive
            % Max Calculations
            [cmax.(cangle).(crep),s] = max(fdata.(cangle).(crep)(:,2));
            [c,~] = size(fdata.(cangle).(crep)(:,2));
            % False peak check
            if s < 50 % if max if in first 1/2 second
                cmin = min(fdata.(cangle).(crep)(s:s+50,2)); % find in half second after peak
                normal_avg = fdata.(cangle).(crep)(150,2); % take value at 1.5 seconds
                if (cmax.(cangle).(crep) - cmin) > peakDropMax && (normal_avg - cmin) > secondPeak % threshold for identifying false peak
                    plot((fdata.(cangle).(crep)(:,1)),fdata.(cangle).(crep)(:,2)); % plots if there is false peak
                    % data from metadata to get joint and direction
                    info = trialDataImport(filename);
                    joint = string(info(19)) ; % Joint
                    dof = string(info(20)) ; % Biodex designation
                    bdirection  = string(info(22) ); % Direction of movement
                    if contains(joint,'Hip')==1
                        if contains(dof, 'Extension') && contains(bdirection, 'TOWARDS')
                            match = 'ex' ; % Assigns extension based on biodex direction
                        elseif contains(dof, 'Extension') && contains(bdirection, 'AWAY')
                            match = 'fx' ; % Assigns flexion based on biodex direction
                        elseif contains(dof, 'Abduction') && contains(bdirection, 'TOWARDS')
                            match = 'ad' ; % Assigns adduction based on biodex direction
                        else
                            match = 'ab' ; % Assigns abduction based on biodex direction
                        end
                    end
                    % user input on if peak should be discarded
                    %disp(['False peak detected at ', joint, match, num2str(cangle), num2str(crep)]);
                    fprintf('False peak detected at %s %s %s %s\n', joint, match, num2str(cangle), num2str(crep));
                    user_input = input("Do you want to discard peak? (y/n)", 's');
                    if strcmpi(user_input,'y')% discard peak and continue on with rest of code
                        fdata.(cangle).(crep) = fdata.(cangle).(crep)(51:end,:); % delete first half second of trial
                        hold on
                        plot((fdata.(cangle).(crep)(:,1)),fdata.(cangle).(crep)(:,2),'r');
                        legend('False Peak','Saved Data','Location','southeast')
                        pause(5)
                        close all
                        % Max Calculations
                        [cmax.(cangle).(crep),s] = max(-fdata.(cangle).(crep)(:,2));
                        [c,~] = size(fdata.(cangle).(crep)(:,2));
                    else
                        disp("Keeping peak");
                    end
                end
            end
            if s < 50
                mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(1:100,2));
            else
                mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s-49:s+50,2));
            end
            if s > c-100
                swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(end-100:end,2));
            else
                swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s:s+99,2));
            end
        elseif sum(fdata.(cangle).(crep)(:,2)) < 0 % Checks to see if the data is negative
            % Max Calculations
            [cmax.(cangle).(crep),s] = max(-fdata.(cangle).(crep)(:,2));
            [c,~] = size(fdata.(cangle).(crep)(:,2));
            % False peak check
            if s < 50 % if max if in first 1/2 second
                cmin = min(-fdata.(cangle).(crep)(s:s+50,2)); % find in half second after peak
                normal_avg = -fdata.(cangle).(crep)(150,2); % take value at 1.5 seconds
                if (cmax.(cangle).(crep) - cmin) > peakDropMax && (normal_avg - cmin) > secondPeak % threshold for identifying false peak
                    plot((fdata.(cangle).(crep)(:,1)),fdata.(cangle).(crep)(:,2)); % plots if there is false peak
                    % data from metadata to get joint and direction
                    info = trialDataImport(filename);
                    joint = string(info(19)) ; % Joint
                    dof = string(info(20)) ; % Biodex designation
                    bdirection  = string(info(22) ); % Direction of movement
                    if contains(joint,'Hip')==1
                        if contains(dof, 'Extension') && contains(bdirection, 'TOWARDS')
                            match = 'ex' ; % Assigns extension based on biodex direction
                        elseif contains(dof, 'Extension') && contains(bdirection, 'AWAY')
                            match = 'fx' ; % Assigns flexion based on biodex direction
                        elseif contains(dof, 'Abduction') && contains(bdirection, 'TOWARDS')
                            match = 'ad' ; % Assigns adduction based on biodex direction
                        else
                            match = 'ab' ; % Assigns abduction based on biodex direction
                        end
                    end
                    % user input on if peak should be discarded
                    %disp(['False peak detected at ', joint, match, num2str(cangle), num2str(crep)]);
                    fprintf('False peak detected at %s %s %s %s\n', joint, match, num2str(cangle), num2str(crep));
                    user_input = input("Do you want to discard peak? (y/n)", 's');
                    if strcmpi(user_input,'y')% discard peak and continue on with rest of code
                        fdata.(cangle).(crep) = fdata.(cangle).(crep)(51:end,:); % delete first half second of trial
                        hold on
                        plot((fdata.(cangle).(crep)(:,1)),fdata.(cangle).(crep)(:,2),'r');
                        legend('False Peak','Saved Data','Location','southeast')
                        pause(5)
                        close all
                        % Max Calculations
                        [cmax.(cangle).(crep),s] = max(-fdata.(cangle).(crep)(:,2));
                        [c,~] = size(fdata.(cangle).(crep)(:,2));
                    else
                        disp("Keeping peak");
                    end
                end
            end
            if s < 50
                mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(1:100,2));
            else
                mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s-49:s+50,2));
            end
            if s > c-100
                swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(end-100:end,2));
            else
                swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s:s+99,2));
            end
        else % Takes care of any empty fields (lost data, excluded data, ect)
            cmax.(cangle).(crep) = 0; % Sets the empty field to 0 to avoid issues for max and average
        end
    end
    for na = 2:2:length(angles)
        ind.(['a',num2str(angles(1,na))]) = (tbl.Set==na) ;
        cangle = (['a',num2str(angles(1,na))]) ; % Sets current angle
        crep = ['rep',num2str(2)] ; % Sets current rep
        itrial = (ind.(cangle)); % Creates the trial to be used
        data.(cangle).(crep) = [tbl.mSec(itrial),tbl.TORQUE(itrial)] ; % Saves data for time and torque
        % Data Filter
        w_coff1 =20 ; w_samp = 100 ;
        [b1,a1] = butter(2,(w_coff1/(w_samp/2)),'low') ;
        fdata.(cangle).(crep)(:,2) = filtfilt(b1,a1,data.(cangle).(crep)(:,2));
        fdata.(cangle).(crep)(:,1) = data.(cangle).(crep)(:,1);
        if sum(fdata.(cangle).(crep)(:,2)) > 0 % Checks to see if the data is positive
            % Max Calculations
            [cmax.(cangle).(crep),s] = max(fdata.(cangle).(crep)(:,2)) ;
            [c,~] = size(fdata.(cangle).(crep)(:,2));
            % False peak check
            if s < 50 % if max if in first 1/2 second
                cmin = min(fdata.(cangle).(crep)(s:s+50,2)); % find in half second after peak
                normal_avg = fdata.(cangle).(crep)(150,2); % take value at 1.5 seconds
                if (cmax.(cangle).(crep) - cmin) > peakDropMax && (normal_avg - cmin) > secondPeak % threshold for identifying false peak
                    plot((fdata.(cangle).(crep)(:,1)),fdata.(cangle).(crep)(:,2)); % plots if there is false peak
                    % data from metadata to get joint and direction
                    info = trialDataImport(filename);
                    joint = string(info(19)) ; % Joint
                    dof = string(info(20)) ; % Biodex designation
                    bdirection  = string(info(22) ); % Direction of movement
                    if contains(joint,'Hip')==1
                        if contains(dof, 'Extension') && contains(bdirection, 'TOWARDS')
                            match = 'ex' ; % Assigns extension based on biodex direction
                        elseif contains(dof, 'Extension') && contains(bdirection, 'AWAY')
                            match = 'fx' ; % Assigns flexion based on biodex direction
                        elseif contains(dof, 'Abduction') && contains(bdirection, 'TOWARDS')
                            match = 'ad' ; % Assigns adduction based on biodex direction
                        else
                            match = 'ab' ; % Assigns abduction based on biodex direction
                        end
                    end
                    % user input on if peak should be discarded
                    %disp(['False peak detected at ', joint, match, num2str(cangle), num2str(crep)]);
                    fprintf('False peak detected at %s %s %s %s\n', joint, match, num2str(cangle), num2str(crep));
                    user_input = input("Do you want to discard peak? (y/n)", 's');
                    if strcmpi(user_input,'y')% discard peak and continue on with rest of code
                        fdata.(cangle).(crep) = fdata.(cangle).(crep)(51:end,:); % delete first half second of trial
                        hold on
                        plot((fdata.(cangle).(crep)(:,1)),fdata.(cangle).(crep)(:,2),'r');
                        legend('False Peak','Saved Data','Location','southeast')
                        pause(5)
                        close all
                        % Max Calculations
                        [cmax.(cangle).(crep),s] = max(-fdata.(cangle).(crep)(:,2));
                        [c,~] = size(fdata.(cangle).(crep)(:,2));
                    else
                        disp("Keeping peak");
                    end
                end
            end
            if s < 50
                mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(1:100,2));
            else
                mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s-49:s+50,2));
            end
            if s > c-100
                swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(end-100:end,2));
            else
                swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s:s+99,2));
            end
        elseif sum(fdata.(cangle).(crep)(:,2)) < 0 % Checks to see if the data is negative
            % Max Calculations
            [cmax.(cangle).(crep),s] = max(-fdata.(cangle).(crep)(:,2));
            [c,~] = size(fdata.(cangle).(crep)(:,2));
            % False peak check
            if s < 50 % if max if in first 1/2 second
                cmin = min(-fdata.(cangle).(crep)(s:s+50,2)); % find min half second after peak
                normal_avg = -fdata.(cangle).(crep)(150,2); % take value at 1.5 seconds
                if (cmax.(cangle).(crep) - cmin) > peakDropMax && (normal_avg - cmin) > secondPeak % threshold for identifying false peak
                    plot((fdata.(cangle).(crep)(:,1)),fdata.(cangle).(crep)(:,2));  % plots if there is false peak
                    % data from metadata to get joint and direction
                    info = trialDataImport(filename);
                    joint = string(info(19)) ; % Joint
                    dof = string(info(20)) ; % Biodex designation
                    bdirection  = string(info(22) ); % Direction of movement
                    if contains(joint,'Hip')==1
                        if contains(dof, 'Extension') && contains(bdirection, 'TOWARDS')
                            match = 'ex' ; % Assigns extension based on biodex direction
                        elseif contains(dof, 'Extension') && contains(bdirection, 'AWAY')
                            match = 'fx' ; % Assigns flexion based on biodex direction
                        elseif contains(dof, 'Abduction') && contains(bdirection, 'TOWARDS')
                            match = 'ad' ; % Assigns adduction based on biodex direction
                        else
                            match = 'ab' ; % Assigns abduction based on biodex direction
                        end
                    end
                    % user input on if peak should be discarded
                    %disp(['False peak detected at ', joint, match, num2str(cangle), num2str(crep)]);
                    fprintf('False peak detected at %s %s %s %s\n', joint, match, num2str(cangle), num2str(crep));
                    user_input = input("Do you want to discard peak? (y/n)", 's');
                    if strcmpi(user_input,'y')% discard peak and continue on with rest of code
                        fdata.(cangle).(crep) = fdata.(cangle).(crep)(51:end,:); % delete first half second of trial
                        hold on
                        plot((fdata.(cangle).(crep)(:,1)),fdata.(cangle).(crep)(:,2),'r');
                        legend('False Peak','Saved Data','Location','southeast')
                        pause(5)
                        close all
                        % Max Calculations
                        [cmax.(cangle).(crep),s] = max(-fdata.(cangle).(crep)(:,2));
                        [c,~] = size(fdata.(cangle).(crep)(:,2));
                    else
                        disp("Keeping peak");
                    end
                end
            end
            if s < 50
                mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(1:100,2));
            else
                mdmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s-49:s+50,2));
            end
            if s > c-100
                swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(end-100:end,2));
            else
                swmax.(cangle).(crep) = mean(-fdata.(cangle).(crep)(s:s+99,2));
            end
        else % Takes care of any empty fields (lost data, excluded data, ect)
            cmax.(cangle).(crep) = 0; % Sets the empty field to 0 to avoid issues for max and average
        end

    end

    for na = 1:2:length(angles)
        cangle = (['a',num2str(angles(1,na))]); % Sets current angle
        pmax.(cangle)(1,1) = max(abs(cmax.(cangle).rep1),abs(cmax.(cangle).rep2));
        tmax.(cangle) = (cmax.(cangle).rep1+cmax.(cangle).rep2)/2; % Manual calculation of the max for each angle
        if pmax.(cangle) == cmax.(cangle).rep1
            mmax.(cangle) = mdmax.(cangle).rep1;
            smax.(cangle) = swmax.(cangle).rep1;
            pmax.(cangle)(1,2) = 1;
        else
            mmax.(cangle) = mdmax.(cangle).rep2;
            smax.(cangle) = swmax.(cangle).rep2;
            pmax.(cangle)(1,2) = 2;
        end
    end
end


%% Sets up Meta Data Analysis
info = trialDataImport(filename);
metadata.subject = string(info(1)); % Subject ID
metadata.joint = string(info(19)); % Joint
metadata.dof = string(info(20)); % Biodex designation
metadata.bdirection  = string(info(22) ); % Direction of movement
if contains(metadata.joint,'Ankle')==1
    if contains(metadata.dof, 'Plantar') && contains(metadata.bdirection, 'TOWARDS')
        metadata.match = 'df'; % Assigns dorsiflexion based on biodex direction
    else
        metadata.match = 'pf'; % Assigns plantar flexion based on biodex direction
    end
elseif contains(metadata.joint,'Knee')==1
    if contains(metadata.dof, 'Extension') && contains(metadata.bdirection, 'TOWARDS')
        metadata.match = 'fx'; % Assigns flexion based on biodex direction
    else
        metadata.match = 'ex'; % Assigns extension based on biodex direction
    end
elseif  contains(metadata.joint,'Hip')==1
    if contains(metadata.dof, 'Extension') && contains(metadata.bdirection, 'TOWARDS')
        metadata.match = 'ex'; % Assigns extension based on biodex direction
    elseif contains(metadata.dof, 'Extension') && contains(metadata.bdirection, 'AWAY')
        metadata.match = 'fx'; % Assigns flexion based on biodex direction
    elseif contains(metadata.dof, 'Abduction') && contains(metadata.bdirection, 'TOWARDS')
        metadata.match = 'ad'; % Assigns adduction based on biodex direction
    else
        metadata.match = 'ab'; % Assigns abduction based on biodex direction
    end
end
end